Teensy restart
samkhal/biped pull request #7
Opened 2016-12-10 19:15 UTC by gardamerinos

Starting Teensy code from scratch

2016-12-10 19:17 UTC, gardamerinos commented
Basic functionality: be able to send teensy commands over lcm and return stuff.

2016-12-11 00:33 UTC, samkhal requested changes

2016-12-11 00:33 UTC, samkhal commented on serial_communication/onboard/onboard/ROM_DATA.h
> +};
Please please don't do this kind of thing. Now you have an array and an enum with the exact same info... Use arrays, please.

2016-12-11 00:33 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  int address2 = ROM[(link*2) + attribute*6 + 2];
Why 2? Why 6? use constants that explain what you're doing. If you need a 2D array use a 2D array.

2016-12-11 00:33 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
>  void callback(CHANNEL_ID id, commData2Teensy* msg_IN){
callback is very non-descriptive name

2016-12-11 00:33 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +ConstJoint* cjoint_p;
Again, you don't need to define a pointer to the same thing for no reason.

2016-12-11 00:33 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  EEPROM.write(ROM[20+cjoint->link*2], (byte)0);
As above, if you're doing strange index arithmetic, be clear about what's happening.

2016-12-11 00:43 UTC, LoganTutt requested changes

2016-12-11 00:43 UTC, LoganTutt commented on serial_communication/onboard/onboard/ConstJoint.h
> +struct ConstJoint {
I think the name ConstJoint is unclear as to what this struct represents. It sounds like a joint that will never move, not the constants associated with the joint. I think something like JointParams or JointAttributes would make more sense.

Additionally, there is a lot in this struct, which should probably split into multiple substructures

2016-12-11 00:43 UTC, LoganTutt commented on serial_communication/onboard/onboard/ConstJoint.h
> +const ConstJoint JointTable[13]= {
Why are we using 1 index for the joints instead of 0 index?

2016-12-11 06:26 UTC, Ari-Goodman commented on serial_communication/BipedTeensyLCM/fix_std.hpp
> +    while(1);
just making sure this is meant to be here

2016-12-11 06:45 UTC, samkhal commented on serial_communication/BipedTeensyLCM/fix_std.hpp
> +    while(1);
Yeah I wrote that, it was just copied over and shouldn't be in this commit. Yeah it's correct, the function is [[noreturn]] which means the compiler complains if it is capable of returning.

2016-12-13 20:28 UTC, samkhal requested changes

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  Joint joints[numOfJoints];
Add include guards for ROM_Data, include it here for numOfJoints

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  uint16_t maxPot;
Get rid of these variables

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +    SEND_TRAJECTORY,
Should probably be "receive_trajectory", since we're in the teensy's perspective.

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  bool EMERGENCY = false;
Should probably be replaced by a an emergency_stop function instead of a flag.

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  uint32_t dataLength;
var not needed

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  bool OutOfRange;
Get rid of this global

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  volatile bool allowPD = true; //flag for allowing the control
For now, let's get rid of residual send-trajectory timing stuff.

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  }
All of these should be in the Joint class

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +
All of the above in the class too

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  // }
Get rid of this

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/Joint.hpp
> +    int setPoint;
Make these private and add all PID functionality to Joint.

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/Joint.hpp
> +    void setPotCabling(int potCabling_) {potCabling = potCabling_;};
Last 4 setters are unnecessary, don't have setters for things that never change.

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/Joint.hpp
> +    int enablePin;
Make as many things `const` as you can

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/Joint.hpp
> +    void setZeroPot(int zeroPot_){zeroPot = zeroPot_;}
Joint should handle all of this, we don't want these functions. Joints can calibrate themselves.

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/Joint.hpp
> +
Get rid of almost all of these getters.

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/Joint.hpp
> +};
make const if you really want

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  }
Move to class

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +  }
Move to class

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +      command = commData2Teensy::STOP;
Command should only be set from the callback

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +      PIDcontrol((&joints[currLocalJoint])->setPoint, &joints[currLocalJoint]);
`.setPoint`

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +void stateAssignment(){
Pass command to here.

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +      case commData2Teensy::WAIT:
Don't need a "WAIT" command.

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/ROM_DATA.h
> +const int MEM_BYTES = 2;
sizeof(uint16_t)

2016-12-13 20:28 UTC, samkhal commented on serial_communication/onboard/onboard/main.cpp
> +    val = val + (EEPROM.read(address2) << 8);
Use `get()` and `put()` instead of `read()` and `write()`

2016-12-13 23:45 UTC, closed without merging